apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-kube
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-kube
  template:
    metadata:
      labels:
        app: react-kube
    spec:
      containers:
      - name: react-kube
        image: mythicalmax/react-kube
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: react-kube
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 31000
  selector:
    app: react-kube